name: Github Action Demo
on: 
  push:
    branches:
       - main
     paths-ignore: [.github/**]
 pull_request:
   branches: [main]
   schedule:
    - corn: '15 6 * * 0'
    workflow_dispatch:
  jobs:
      Buils:
       -run-on: |
          echo "The job was tiggered by event: ${{ github.event_name }}"
          echo "The name of your branch is ${{ github.event_name }}"
       
      - uses: action/checkout@v3.3.0
      -run: tree -a
