name: Github Action Demo
on: 
  push:
    branches:
     - main
     paths-ignore: [.github/**]
   pull_request:
   branches: [main]
   schedule:
    -corn: '15 6 * *'
    workflow_dispatch:
    jobs:
     buils:
      -run: |
      echo "fjhhfjgffg: ${{ github.event_name }}"
      echo "fjhhfjgffg: ${{ github.event_name }}"
      - uses: action/checkout@v3.3.0
      -run: tree -a
